//! Cryptographic protocol types and trait interfaces.

use serde::{Deserialize, Serialize};
use zeroize::Zeroize;

/// A Publisher's long-term public key (Ed25519), used for identity and signing.
pub type PublisherPublicKey = [u8; 32];

/// A Publisher's X25519 public key, used for ECDH key agreement.
pub type X25519PublicKey = [u8; 32];

/// An ephemeral X25519 public key generated by the Creator per upload session.
pub type EphemeralPublicKey = [u8; 32];

/// AES-256-GCM session key derived from ECDH + HKDF.
#[derive(Clone, Zeroize)]
#[zeroize(drop)]
pub struct SessionKey(pub [u8; 32]);

/// Base nonce for AES-256-GCM. Per-chunk nonce is derived as:
/// `nonce = nonce_base XOR chunk_index` (first 4 bytes of nonce XORed).
#[derive(Clone)]
pub struct NonceBase(pub [u8; 12]);

/// Information needed to initialize an upload session on the Publisher side.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UploadSessionInit {
    /// Creator's ephemeral X25519 public key for this session.
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub ephemeral_pubkey: EphemeralPublicKey,
    /// Which Publisher key was targeted.
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub publisher_pubkey: PublisherPublicKey,
    /// Random session identifier.
    #[serde(with = "crate::serde_b64::fixed_16")]
    pub session_id: [u8; 16],
    /// Total number of chunks the Creator will send.
    pub total_chunks: u32,
    /// BLAKE3 hash of the full sanitized video.
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub content_hash: [u8; 32],
}
