use serde::{Deserialize, Serialize};
use std::net::SocketAddr;

/// A single onion layer plaintext after successful decrypt/open.
///
/// If `next_hop` is `Some(addr)`, the current node is an intermediate relay and
/// must forward `inner` to `addr`.
///
/// If `next_hop` is `None`, this node is the terminal destination and `inner`
/// should be decoded as the destination payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnionLayer {
    pub next_hop: Option<SocketAddr>,
    #[serde(with = "crate::serde_b64::bytes")]
    pub inner: Vec<u8>,
    /// Distributed trace chain propagated end-to-end by the initiator.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

/// Public identity for one hop in a route.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HopInfo {
    pub addr: SocketAddr,
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub identity_pub: [u8; 32],
}

/// Terminal payload delivered at the final hop.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkPayload {
    pub chunk_id: u64,
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub hash: [u8; 32],
    #[serde(with = "crate::serde_b64::bytes")]
    pub chunk: Vec<u8>,
    pub return_path: Vec<HopInfo>,
    /// End-to-end trace chain generated by the creator.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    #[serde(default)]
    pub send_timestamp_ms: u64,
    #[serde(default)]
    pub total_chunks: u32,
    #[serde(default)]
    pub chunk_index: u32,
}

/// Terminal ACK payload decrypted by the creator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AckPayload {
    pub chunk_id: u64,
    #[serde(with = "crate::serde_b64::fixed_32")]
    pub hash: [u8; 32],
    /// End-to-end trace chain copied from chunk payload and extended on return.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    #[serde(default)]
    pub send_timestamp_ms: u64,
    #[serde(default)]
    pub received_timestamp_ms: u64,
    #[serde(default)]
    pub total_chunks: u32,
    #[serde(default)]
    pub chunk_index: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, Serialize, Deserialize)]
    struct LegacyOnionLayer {
        next_hop: Option<SocketAddr>,
        inner: Vec<u8>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    }

    #[test]
    fn onion_layer_round_trips_and_shrinks_json() {
        let layer = OnionLayer {
            next_hop: Some("10.0.0.1:9001".parse().unwrap()),
            inner: (0u8..=255).cycle().take(1024).collect(),
            trace_id: Some("trace-a -> trace-b".to_string()),
        };

        let encoded = serde_json::to_vec(&layer).unwrap();
        let decoded: OnionLayer = serde_json::from_slice(&encoded).unwrap();
        assert_eq!(decoded.next_hop, layer.next_hop);
        assert_eq!(decoded.inner, layer.inner);
        assert_eq!(decoded.trace_id, layer.trace_id);

        let legacy = LegacyOnionLayer {
            next_hop: layer.next_hop,
            inner: layer.inner.clone(),
            trace_id: layer.trace_id.clone(),
        };
        let legacy_encoded = serde_json::to_vec(&legacy).unwrap();

        assert!(
            encoded.len() < legacy_encoded.len() / 2,
            "expected compact encoding to materially reduce onion JSON: compact={} legacy={}",
            encoded.len(),
            legacy_encoded.len()
        );
    }
}
